In [17]:
import pandas as pd

In [1]:
#This is to clean up product data and ingredient data.
#We want to make two tables.
#one table contains the product id and the ingredient id it contains.
#The second table is the ingredient id and ingredients

In [18]:
#read csv
sephora = pd.read_csv('sephora_website_dataset-unique.csv')
ingredients = pd. read_csv("ingredients.csv")

In [19]:
#Separate each ingredient: the ingredients of the product are put together and connected with "-"
sephora["ingredients"] = sephora["ingredients"].str.split('-')

In [20]:
#Rearrange the product table so that each row has only one ingredient
split_s = sephora.explode('ingredients')
split_s

,id,brand,category,name,size,rating,number_of_reviews,love,price,value_price,...,MarketingFlags,MarketingFlags_content,options,details,how_to_use,ingredients,online_only,exclusive,limited_edition,limited_time_offer
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,True,online only,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Alcohol,1,0,0,0
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,True,online only,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Water,1,0,0,0
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,True,online only,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Fragrance,1,0,0,0
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,True,online only,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Limonene,1,0,0,0
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,True,online only,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Linalool,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9165,2236750,SEPHORA COLLECTION,Tinted Moisturizer,Weekend Warrior Tone Up Cream,0.946 oz/ 28 mL,0.0,0,445,16.0,16.0,...,True,exclusive,no options,What it is: A weightless complexion booster- i...,Suggested Usage:-Use this product as the last ...,Ci 77499 (Iron Oxides),0,1,0,0
9165,2236750,SEPHORA COLLECTION,Tinted Moisturizer,Weekend Warrior Tone Up Cream,0.946 oz/ 28 mL,0.0,0,445,16.0,16.0,...,True,exclusive,no options,What it is: A weightless complexion booster- i...,Suggested Usage:-Use this product as the last ...,Citrus Japonica Fruit Extract,0,1,0,0
9165,2236750,SEPHORA COLLECTION,Tinted Moisturizer,Weekend Warrior Tone Up Cream,0.946 oz/ 28 mL,0.0,0,445,16.0,16.0,...,True,exclusive,no options,What it is: A weightless complexion booster- i...,Suggested Usage:-Use this product as the last ...,Citric Acid.,0,1,0,0
9166,50,SEPHORA COLLECTION,no category,Gift Card,no size,5.0,46,0,50.0,50.0,...,False,0,no options,What it is:- Available in denominations of $10...,no instructions,unknown,0,0,0,0
9167,304,SEPHORA COLLECTION,no category,Happy Birthday Gift Card,no size,0.0,0,0,50.0,50.0,...,False,0,no options,What it is:\n- Available in denominations of $...,no instructions,unknown,0,0,0,0

In [21]:
#Match the hazardous characteristics of each ingredient
leftjoin=pd.merge(split_s,ingredients,left_on='ingredients',right_on='chemical_name',how='left')
leftjoin.head()

,id,brand,category,name,size,rating,number_of_reviews,love,price,value_price,...,options,details,how_to_use,ingredients,online_only,exclusive,limited_edition,limited_time_offer,chemical_name,hazard_traits
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Alcohol,1,0,0,0,NaN,NaN
1,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Water,1,0,0,0,NaN,NaN
2,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Fragrance,1,0,0,0,NaN,NaN
3,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Limonene,1,0,0,0,NaN,NaN
4,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Linalool,1,0,0,0,NaN,NaN

In [22]:
#Only keep the ingredients and its hazad traits.
harmful_ingredients = leftjoin[["ingredients", "hazard_traits"]]

In [23]:
#There are some same ingredients in different products, so delete duplicate ingredients
harmful_ingredients = harmful_ingredients.drop_duplicates('ingredients', keep='first')

In [24]:
#Change the name of the columns
harmful_ingredients = harmful_ingredients.rename(columns={ "ingredients": 'chemical_name'})
harmful_ingredients = harmful_ingredients.rename(columns={ "hazard_traits": 'hazard_trait'})

#Add id to each ingredient
harmful_ingredients.insert(0, 'ingredient_id', harmful_ingredients.index + 1)
harmful_ingredients

,ingredient_id,chemical_name,hazard_trait
0,1,Alcohol,NaN
1,2,Water,NaN
2,3,Fragrance,NaN
3,4,Limonene,NaN
4,5,Linalool,NaN
...,...,...,...
368024,368025,Linalool . (+/,NaN
368028,368029,CI 15850 (Red 6 Lake/Red 7/Red 7 Lake),NaN
368030,368031,CI 45410 (Red 28 Lake).Colorful Gloss Balm Ho...,NaN
368048,368049,CI 15850 (Red 7/Red 7 Lake/Red 6 Lake),NaN
368050,368051,CI 45380 (Red 21 Lake),NaN

In [25]:
# Cleanup ingredient name
harmful_ingredients['chemical_name'] = harmful_ingredients['chemical_name'].str.replace('*', '', regex = False)

In [26]:
#Change the hazard trait of non-hazardous ingredients to "NULL"
harmful_ingredients=harmful_ingredients.fillna("NULL")
harmful_ingredients

,ingredient_id,chemical_name,hazard_trait
0,1,Alcohol,NULL
1,2,Water,NULL
2,3,Fragrance,NULL
3,4,Limonene,NULL
4,5,Linalool,NULL
...,...,...,...
368024,368025,Linalool . (+/,NULL
368028,368029,CI 15850 (Red 6 Lake/Red 7/Red 7 Lake),NULL
368030,368031,CI 45410 (Red 28 Lake).Colorful Gloss Balm Ho...,NULL
368048,368049,CI 15850 (Red 7/Red 7 Lake/Red 6 Lake),NULL
368050,368051,CI 45380 (Red 21 Lake),NULL

In [27]:
# download csv
harmful_ingredients.to_csv('harmful_ingredients.csv', sep=',',index=False)

In [28]:
#Product id and their ingredients
product_ingredients = leftjoin[["id", "ingredients"]]
product_ingredients

             id                     ingredients
0       2218774                        Alcohol
1       2218774                           Water
2       2218774                       Fragrance
3       2218774                        Limonene
4       2218774                        Linalool
...         ...                             ...
368088  2236750          Ci 77499 (Iron Oxides)
368089  2236750   Citrus Japonica Fruit Extract
368090  2236750                    Citric Acid.
368091       50                         unknown
368092      304                         unknown

[368093 rows x 2 columns]

In [29]:
#Match ingredients and their id to connect product id and ingredient id
product_ingredients=pd.merge(product_ingredients,harmful_ingredients,left_on='ingredients',right_on='chemical_name',how='left')
product_ingredients

,id,ingredients,ingredient_id,chemical_name,hazard_trait
0,2218774,Alcohol,1.0,Alcohol,NULL
1,2218774,Water,2.0,Water,NULL
2,2218774,Water,164490.0,Water,NULL
3,2218774,Fragrance,3.0,Fragrance,NULL
4,2218774,Fragrance,25807.0,Fragrance,NULL
...,...,...,...,...,...
562179,2236750,Ci 77499 (Iron Oxides),28338.0,Ci 77499 (Iron Oxides),NULL
562180,2236750,Citrus Japonica Fruit Extract,254589.0,Citrus Japonica Fruit Extract,NULL
562181,2236750,Citric Acid.,9510.0,Citric Acid.,NULL
562182,50,unknown,84.0,unknown,NULL
562183,304,unknown,84.0,unknown,NULL

In [31]:
#Only keep product id and ingredient id
product_ingredients = product_ingredients[["id", "ingredient_id"]]
product_ingredients = product_ingredients.rename(columns={ "id": 'product_id'})
product_ingredients

        product_id  ingredient_id
0          2218774            1.0
1          2218774            2.0
2          2218774       164490.0
3          2218774            3.0
4          2218774        25807.0
...            ...            ...
562179     2236750        28338.0
562180     2236750       254589.0
562181     2236750         9510.0
562182          50           84.0
562183         304           84.0

[562184 rows x 2 columns]

In [32]:
product_ingredients.to_csv('product_ingredients.csv', sep=',',index=False)